highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Philippe Tring's Resume
name: Philippe Tring
email: philippetring@gmail.com
email_full: mailto:philippetring+vitae@gmail.com
github: gnirt
twitter: philippetring
tel: +336 11244514
tel_full: tel:+33(0)6 11 24 45 14
google_maps: 'https://www.google.com/maps/place/Paris,+France'
address: Somewhere
postcode: in
city: Paris
country: France
google_analytics: UA-38611641-2
